### PR TITLE
18 support

### PR DESCRIPTION
**Pull request by nickvergessen**
- [ ] UI is broken, the input field says: `<a href="0">[object HTMLInputElement]</a>`

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
@juliushaertl "vuelius" maybe you can help? :heart:

**Comment by nickvergessen** [comment]
Sadly no Vue here yet

**Comment by juliushaertl** [comment]
@nickvergessen Are you referring to the share link input? Works for me:

image

**Comment by rullzer** [comment]
Btw, if somebody wants to move this to vue etc. All help is welcome ;) this is just hacked together now :P

**Comment by e-alfred** [comment]
I installed 0.3.0 from the app store and it works as expected, no bug with the input field. Can you merge this PR and release a new version to the app store?

**Comment by e-alfred** [comment]
I tested the app on 18.0.2, the app works as intended. @rullzer maybe you can make a release now?

**Pull request merged**
